#!/bin/bash

# Extract values using jq
name=$(jq -r '.name' pikachu.json | sed 's/.*/\u&/') # Capitalize first letter
type=$(jq -r '.types[0].type.name' pikachu.json | sed 's/.*/\u&/')
height=$(jq -r '.height' pikachu.json | awk '{printf "%.1f", $1/10}')
weight=$(jq -r '.weight' pikachu.json | awk '{printf "%.0f", $1/10}')

# Print formatted output
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
